waifu2x_caffe:
  path: 'C:\Users\K4YT3X\AppData\Local\video2x\waifu2x-caffe\waifu2x-caffe-cui'
  input_extention_list: null
  output_extention: null
  mode: noise_scale
  scale_ratio: null
  scale_width: null
  scale_height: null
  noise_level: 3
  process: gpu
  crop_size: 128
  output_quality: -1
  output_depth: 8
  batch_size: 1
  gpu: 0
  tta: 0
  input_path: null
  output_path: null
  model_dir: null
  crop_w: null
  crop_h: null
waifu2x_converter_cpp:
  path: 'C:\Users\K4YT3X\AppData\Local\video2x\waifu2x-converter-cpp\waifu2x-converter-cpp'
  # list-supported-formats: null
  # list-opencv-formats: null
  # list-processor
  output-format: progress_bar_exit_signal
  png-compression: 5
  image-quality: -1
  block-size: 0
  disable-gpu: false
  force-OpenCL: false
  processor: -1
  jobs: 0
  model-dir: null # models_rgb
  scale-ratio: 2.0
  noise-level: 1
  mode: noise-scale
  log-level: 1
  silent: null
  tta: 0
  # generate-subdir: 0
  # recursive-directory: 0
  output: null
  input: null
waifu2x_ncnn_vulkan:
  path: 'C:\Users\K4YT3X\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan'
  v: null
  i: null
  o: null
  'n': 2
  s: 2
  t: 400
  m: null # default: models-cunet
  g: 0
  j: '1:2:2'
srmd_ncnn_vulkan:
  path: 'C:\Users\K4YT3X\AppData\Local\video2x\srmd-ncnn-vulkan\srmd-ncnn-vulkan'
  v: null
  i: null
  o: null
  'n': 3
  s: 2
  t: 400
  m: null # default: models-srmd
  g: 0
  j: '1:2:2'
  x: null
anime4kcpp:
  path: 'C:\Users\k4yt3x\AppData\Local\video2x\anime4kcpp\CLI\Anime4KCPP_CLI\Anime4KCPP_CLI'
  input: null
  output: null
  passes: 2
  pushColorCount: 2
  strengthColor: 0.3
  strengthGradient: 1
  zoomFactor: 2
  threads: 16
  fastMode: null
  videoMode: true
  preview: null
  preProcessing: null
  postProcessing: null
  preFilters: 4
  postFilters: 40
  GPUMode: null
  listGPUs: null
  platformID: 0
  deviceID: 0
ffmpeg:
  ffmpeg_path: 'C:\Users\K4YT3X\AppData\Local\video2x\ffmpeg-latest-win64-static\bin'
  video_to_frames:
    output_options:
      '-qscale:v': null
      '-pix_fmt': rgba64be
    '-hwaccel': auto
    '-y': true
  frames_to_video:
    input_options:
      '-qscale:v': null
      '-qscale:a': null
      '-f': image2
    output_options:
      '-vcodec': libx264
      '-crf': 17
      '-b:v': null
      '-pix_fmt': null
    '-hwaccel': auto
    '-y': true
  migrating_tracks:
    output_options:
      '-map':
        - '0:v?'
        - '1:a?'
        - '1:s?'
        - '1:d?'
        - '1:t?'
      '-c': copy
      '-pix_fmt': null
    '-hwaccel': auto
    '-y': true
video2x:
  video2x_cache_directory: null # default: %TEMP%\video2x
  image_format: png
  preserve_frames: false
